[theme]
primaryColor             = "#df6e23ff"
backgroundColor          = "#F8FAFC"
secondaryBackgroundColor = "#E85A3F"
textColor                = "#1E293B"
font                     = "Optima"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
